import Head from "next/head";
import RequestForm from "../components/RequestForm";
import ResponseSection from "../components/ResponseSection";

const Home = () => {
	return (
		<>
			<Head>
				<title>Postman-Redis</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-3/4 mx-auto py-6 h-screen">
				<RequestForm />
				<ResponseSection />
			</div>
		</>
	);
};

export default Home;
